@extends('layouts.app', ['title' => 'Создать таблицу'])

@section('content')
<x-modal variant="editor" title="Создать таблицу" :close-url="route('workspace.tables')"><div class="table-editor-page">
    <form id="table-editor" method="POST" action="{{ route('workspace.tables.store') }}">@csrf
        <div class="editor-details"><label>Название <em>*</em><input name="name" value="{{ old('name') }}" required autofocus></label><label>Количество строк <em>*</em><input id="row-count" type="number" min="0" name="row_count" value="{{ old('row_count', 1) }}" required></label></div>
        <nav class="tabs editor-tabs"><button class="active" type="button" data-tab="structure">Таблица</button><button type="button" data-tab="values">Значения</button><button type="button" data-tab="script">Скрипт</button></nav>
        <section data-panel="structure"><button type="button" class="add-column" id="add-column"><i data-lucide="plus"></i> Добавить</button><div class="reference-table-wrap editor-wrap"><table class="reference-table column-editor"><thead><tr><th>№</th><th>Название</th><th>Тип</th><th title="Обязательное">☆</th><th title="Ключевое">⌁</th><th>Ширина</th><th></th></tr></thead><tbody id="columns-body"></tbody></table></div></section>
        <section data-panel="values" hidden><div class="reference-table-wrap editor-wrap"><table class="reference-table values-editor"><thead id="values-head"></thead><tbody id="values-body"></tbody></table></div></section>
        <section data-panel="script" hidden><label class="script-label">Скрипт<textarea name="script" rows="10">{{ old('script') }}</textarea></label></section>
    </form>
</div><x-slot:actions><button type="submit" form="table-editor">Создать</button><a class="button secondary" href="{{ route('workspace.tables') }}">Отмена</a></x-slot:actions></x-modal>
<template id="column-template"><tr class="column-row"><td class="row-number"></td><td><input class="column-name" required></td><td><select class="column-type"><option>Строка</option><option>Число целое</option><option>Число дробное</option><option>Дата</option><option>Логическое</option><option>Список</option><option>Файлы</option><option>Приложение</option><option>Итератор</option></select><div class="column-settings"></div></td><td class="check-cell"><input class="column-required" type="checkbox" value="1"></td><td class="check-cell"><input class="column-key" type="checkbox" value="1"></td><td><input class="column-width" type="number" min="40" max="1000" value="175"></td><td><button class="icon-button delete-column" type="button"><i data-lucide="trash-2"></i></button></td></tr></template>
<script>
const body=document.getElementById('columns-body'),rows=()=>[...body.querySelectorAll('.column-row')],esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function settings(row){let box=row.querySelector('.column-settings'),type=row.querySelector('.column-type').value;box.innerHTML=type==='Логическое'?'<label>Текст «Да»<input class="setting-yes" value="Да"></label><label>Текст «Нет»<input class="setting-no" value="Нет"></label><label>По умолчанию<select class="setting-default"><option value="1">Да</option><option value="0">Нет</option></select></label>':type==='Список'?'<label>Варианты списка — по одному с новой строки<textarea class="setting-list" rows="3"></textarea></label>':'';}
function names(){rows().forEach((row,i)=>{row.querySelector('.row-number').textContent=i+1;row.querySelector('.column-name').name=`columns[${i}][name]`;row.querySelector('.column-type').name=`columns[${i}][data_type]`;row.querySelector('.column-required').name=`columns[${i}][is_required]`;row.querySelector('.column-key').name=`columns[${i}][is_key]`;row.querySelector('.column-width').name=`columns[${i}][width]`;let yes=row.querySelector('.setting-yes'),no=row.querySelector('.setting-no'),def=row.querySelector('.setting-default'),list=row.querySelector('.setting-list');if(yes)yes.name=`columns[${i}][settings][b1_text]`;if(no)no.name=`columns[${i}][settings][b0_text]`;if(def)def.name=`columns[${i}][settings][default_state]`;if(list)list.name=`columns[${i}][settings][list]`;row.querySelectorAll('.column-value').forEach((v,r)=>v.name=`columns[${i}][values][${r}]`)});lucide.createIcons();values()}
function values(){let count=Math.max(0,+document.getElementById('row-count').value||0),columns=rows(),head=document.getElementById('values-head'),out=document.getElementById('values-body');head.innerHTML='<tr>'+columns.map(r=>`<th>${esc(r.querySelector('input').value||'Без названия')}</th>`).join('')+'</tr>';out.innerHTML=Array.from({length:count},(_,r)=>'<tr>'+columns.map((col,c)=>`<td><input class="value-input" data-c="${c}" data-r="${r}" value="${esc(col.querySelectorAll('.column-value')[r]?.value||'')}"></td>`).join('')+'</tr>').join('');out.querySelectorAll('.value-input').forEach(i=>i.oninput=()=>{let col=rows()[i.dataset.c],v=col.querySelectorAll('.column-value')[i.dataset.r];if(!v){v=document.createElement('input');v.type='hidden';v.className='column-value';col.append(v)}v.value=i.value;names()})}
document.getElementById('add-column').onclick=()=>{let row=document.getElementById('column-template').content.firstElementChild.cloneNode(true);body.append(row);settings(row);row.querySelector('.column-type').onchange=()=>{settings(row);names()};names()};body.onclick=e=>{let b=e.target.closest('.delete-column');if(b){b.closest('tr').remove();names()}};body.oninput=values;document.getElementById('row-count').oninput=values;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(x=>x.hidden=x.dataset.panel!==b.dataset.tab);if(b.dataset.tab==='values')values()});document.getElementById('add-column').click();
</script>
@endsection
