@extends('layouts.app', ['title' => ($creating ?? false) ? 'Создать таблицу' : 'Редактировать таблицу'])

@section('content')
@php($activeTab = $tab ?? 'structure')
<x-modal class="table-edit-modal" variant="editor" :expandable="true" :title="($creating ?? false) ? 'Создать таблицу' : 'Редактировать таблицу'" :close-url="($creating ?? false) ? route('workspace.tables') : route('workspace.tables.show', $table)"><div class="table-workspace table-editor-page">
    <form method="POST" action="{{ ($creating ?? false) ? route('workspace.tables.store') : route('workspace.tables.update', $table) }}" id="table-editor">@csrf @unless($creating ?? false) @method('PUT') @endunless
        <div class="editor-details editor-details-compact"><label><span>Название <em>*</em></span><input name="name" value="{{ old('name', $table->name) }}" required></label><label><span>Количество строк <em>*</em></span><input type="number" min="0" name="row_count" value="{{ old('row_count', $table->row_count) }}" required></label></div>
        <nav class="tabs editor-tabs"><button @class(['active' => $activeTab === 'structure']) type="button" data-tab="structure">Таблица</button><button @class(['active' => $activeTab === 'values']) type="button" data-tab="values">Значения</button><button @class(['active' => $activeTab === 'script']) type="button" data-tab="script">Скрипт</button></nav>
        <section data-panel="structure" @hidden($activeTab !== 'structure')><div class="editor-section-head"><div><x-info-note>Перетаскивайте поле за первую колонку. Отметьте «Результат» для полей результатов тестирования.</x-info-note></div><button type="button" class="add-column" id="add-column"><i data-lucide="plus"></i> Добавить поле</button></div><div class="reference-table-wrap editor-wrap"><table class="reference-table column-editor"><thead><tr><th title="Перетащить поле"><i data-lucide="grip-vertical"></i></th><th title="Результат тестирования"><i data-lucide="list-checks"></i></th><th>Название</th><th>Тип</th><th title="Обязательное поле"><i data-lucide="star"></i></th><th title="Поле доступно для редактирования"><i data-lucide="square-pen"></i></th><th>Ширина</th><th></th></tr></thead><tbody id="columns-body">
            @foreach ($table->columns->sortBy(fn ($column) => [$column->section === 'result' ? 1 : 0, $column->position]) as $column)
            <tr class="column-row" data-settings='@json($column->settings ?? [])'><td class="drag-handle" title="Перетащить поле"><i data-lucide="grip-vertical"></i></td><td class="check-cell"><input class="column-result" type="checkbox" title="Результат тестирования" @checked($column->section === 'result')></td><td><input class="column-name" value="{{ $column->name }}" required></td><td><select class="column-type">@foreach (['Строка','Число целое','Число дробное','Дата','Логическое','Список','Файлы','Приложение','Итератор'] as $type)<option @selected($column->data_type === $type)>{{ $type }}</option>@endforeach</select><div class="column-settings"></div></td><td class="check-cell"><input class="column-required" type="checkbox" title="Обязательное поле" @checked($column->is_required)></td><td class="check-cell"><input class="column-editable" type="checkbox" title="Доступно для редактирования" @checked(! $column->is_readonly)></td><td><input class="column-width" type="number" min="40" max="1000" value="{{ $column->width }}"></td><td><button class="icon-button delete-column" type="button" title="Удалить поле"><i data-lucide="trash-2"></i></button></td></tr>
            @endforeach
        </tbody></table></div></section>
        <section data-panel="values" @hidden($activeTab !== 'values')><div class="reference-table-wrap editor-wrap"><table class="reference-table values-editor"><thead>
            @if ($table->columns->where('section', 'result')->isNotEmpty())
                <tr>@foreach ($table->columns->where('section', 'primary') as $column)<th rowspan="2">{{ $column->name }}</th>@endforeach <th colspan="{{ $table->columns->where('section', 'result')->count() }}">Результаты тестирования</th></tr>
                <tr>@foreach ($table->columns->where('section', 'result') as $column)<th>{{ $column->name }}</th>@endforeach</tr>
            @else
                <tr>@foreach ($table->columns->where('section', 'primary') as $column)<th>{{ $column->name }}</th>@endforeach</tr>
            @endif
        </thead><tbody id="values-body">
            @foreach ($table->default_values ?? [] as $rowIndex => $values)
                <tr>
                    @foreach ($table->columns->where('section', 'primary')->values() as $columnIndex => $column)
                        <td>@include('tables.partials.value-input', ['column' => $column, 'name' => "default_values[$rowIndex][$columnIndex]", 'value' => $values[$columnIndex] ?? '', 'rowNumber' => $rowIndex + 1])</td>
                    @endforeach
                    @foreach ($table->columns->where('section', 'result')->values() as $columnIndex => $column)
                        <td>@include('tables.partials.value-input', ['column' => $column, 'name' => "default_result_values[$rowIndex][0][$columnIndex]", 'value' => $table->default_result_values[$rowIndex][0][$columnIndex] ?? '', 'rowNumber' => $rowIndex + 1])</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody></table></div></section>
        <section data-panel="script" hidden><label class="script-label">Скрипт формул<textarea name="script" rows="12">{{ old('script', $table->script) }}</textarea></label><details class="formula-help"><summary>Справка по формулам</summary><div class="formula-help-content"><p>В ячейке укажите <code>{f1}</code>, а расчёт опишите в скрипте.</p><h3>Запись формулы</h3><pre><code>f.set('1', ВЫРАЖЕНИЕ); // значение для {f1}</code></pre><h3>Доступные переменные</h3><ul><li><code>tests.get('UUID теста')</code> — ранее выполненный тест;</li><li><code>tests.get('UUID теста').tables.get('UUID таблицы')</code> — таблица выбранного теста;</li><li><code>test</code> — текущий тест; <code>table</code> — текущая таблица;</li><li><code>row</code>, <code>col</code> — текущие строка и колонка; <code>sample</code> — номер образца.</li></ul><h3>Получение значений</h3><ul><li><code>table.v[строка][колонка]</code> — ячейка основной части;</li><li><code>table.rv[строка][образец][колонка]</code> — ячейка результатов по образцам.</li></ul><h3>Пример</h3><pre><code>const previous = tests.get('UUID_теста').tables.get('UUID_таблицы'); f.set('1', previous.v[row][2]);</code></pre><p class="muted">Скрипты импортированы из ELMA как исходный текст. Безопасное автоматическое выполнение будет подключено при реализации выполнения тестов.</p></div></details></section>
    </form>
</div><x-slot:service><x-table-service-information :table="$table" /></x-slot:service><x-slot:actions><button type="submit" form="table-editor">{{ ($creating ?? false) ? 'Создать' : 'Сохранить' }}</button><a class="button secondary" href="{{ ($creating ?? false) ? route('workspace.tables') : route('workspace.tables.show', $table) }}">Отмена</a>@unless($creating ?? false)<button class="danger" type="button" id="delete-toggle">Удалить</button>@endunless</x-slot:actions></x-modal>
<x-modal id="delete-modal" variant="confirm" title="Удалить таблицу?" :hidden="true" close-button-id="delete-cancel"><p class="muted">Будут удалены все поля и значения.</p><form id="delete-table-form" method="POST" action="{{ route('workspace.tables.destroy', $table) }}">@csrf @method('DELETE')</form><x-slot:actions><button class="danger" type="submit" form="delete-table-form">Удалить</button><button class="secondary" type="button" id="delete-cancel-footer">Отмена</button></x-slot:actions></x-modal>
<template id="column-template"><tr class="column-row" data-settings="{}"><td class="drag-handle" title="Перетащить поле"><i data-lucide="grip-vertical"></i></td><td class="check-cell"><input class="column-result" type="checkbox" title="Результат тестирования"></td><td><input class="column-name" required></td><td><select class="column-type"><option>Строка</option><option>Число целое</option><option>Число дробное</option><option>Дата</option><option>Логическое</option><option>Список</option><option>Файлы</option><option>Приложение</option><option>Итератор</option></select><div class="column-settings"></div></td><td class="check-cell"><input class="column-required" type="checkbox" title="Обязательное поле"></td><td class="check-cell"><input class="column-editable" type="checkbox" title="Доступно для редактирования" checked></td><td><input class="column-width" type="number" min="40" max="1000" value="175"></td><td><button class="icon-button delete-column" type="button"><i data-lucide="trash-2"></i></button></td></tr></template>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/theme/material-darker.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.16/mode/javascript/javascript.min.js"></script>
<script>
const editor=document.getElementById('table-editor'),body=document.getElementById('columns-body');
let formulaEditor;
function initFormulaEditor(){const textarea=editor.querySelector('[name="script"]');if(!textarea||!window.CodeMirror||formulaEditor)return;formulaEditor=CodeMirror.fromTextArea(textarea,{mode:'javascript',theme:'material-darker',lineNumbers:true,indentUnit:2,tabSize:2,lineWrapping:true});}
initFormulaEditor();
function renderSettings(row){let data={};try{data=JSON.parse(row.dataset.settings||'{}')}catch{}let box=row.querySelector('.column-settings'),type=row.querySelector('.column-type').value;if(type==='Список'){let list=Array.isArray(data.list)?data.list:[];box.innerHTML=Array.from({length:Math.max(4,list.length+1)},(_,i)=>`<input class="setting-list" placeholder="Вариант ${i+1}" value="${String(list[i]||'').replaceAll('&','&amp;').replaceAll('"','&quot;')}">`).join('')}else if(type==='Логическое'){box.innerHTML=`<input class="setting-yes" placeholder="Текст для Да" value="${data.b1_text||'Да'}"><input class="setting-no" placeholder="Текст для Нет" value="${data.b0_text||'Нет'}">`}else box.innerHTML=''}
function hidden(row,className){let item=row.querySelector('.'+className);if(!item){item=Object.assign(document.createElement('input'),{type:'hidden',className});row.append(item)}return item}
function names(){body.querySelectorAll('.column-row').forEach((row,index)=>{let p=`columns[${index}]`;row.querySelector('.column-name').name=`${p}[name]`;row.querySelector('.column-type').name=`${p}[data_type]`;row.querySelector('.column-required').name=`${p}[is_required]`;row.querySelector('.column-width').name=`${p}[width]`;row.querySelectorAll('.setting-list').forEach(item=>item.name=`${p}[settings][list][]`);let yes=row.querySelector('.setting-yes'),no=row.querySelector('.setting-no');if(yes)yes.name=`${p}[settings][b1_text]`;if(no)no.name=`${p}[settings][b0_text]`;let section=hidden(row,'column-section');section.name=`${p}[section]`;section.value=row.querySelector('.column-result').checked?'result':'primary';let readonly=hidden(row,'column-readonly');readonly.name=`${p}[is_readonly]`;readonly.value=row.querySelector('.column-editable').checked?'0':'1'});window.lucide?.createIcons()}
function prepare(row){renderSettings(row);row.querySelector('.column-type').onchange=()=>{row.dataset.settings='{}';renderSettings(row);names()};row.querySelectorAll('.column-result,.column-editable').forEach(input=>input.onchange=names)}
let movingRow=null;function syncValueRows(){let valuesBody=document.getElementById('values-body');if(!valuesBody)return;let target=Math.max(0,Number(editor.querySelector('[name="row_count"]').value)||0),rows=[...valuesBody.rows];while(rows.length>target)rows.pop().remove();while(rows.length<target&&rows[0]){let row=rows[rows.length-1].cloneNode(true),index=rows.length;row.querySelectorAll('input,select,textarea').forEach(field=>{if(field.name)field.name=field.name.replace(/(default_(?:result_)?values\[)\d+(\])/,`$1${index}$2`);if(field.matches('input:not([type="hidden"])'))field.value='';if(field.matches('select'))field.selectedIndex=0;if(field.type==='hidden'&&field.name?.includes('default_values'))field.value=''});row.querySelectorAll('.inc-value').forEach(item=>item.textContent=index+1);valuesBody.append(row);rows.push(row)}}body.addEventListener('pointerdown',event=>{let handle=event.target.closest('.drag-handle');if(!handle)return;movingRow=handle.closest('.column-row');movingRow.classList.add('is-dragging');handle.setPointerCapture?.(event.pointerId);event.preventDefault()});document.addEventListener('pointermove',event=>{if(!movingRow)return;let target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.column-row');if(target&&target.parentElement===body&&target!==movingRow){let before=event.clientY<target.getBoundingClientRect().top+target.offsetHeight/2;body.insertBefore(movingRow,before?target:target.nextSibling)}});document.addEventListener('pointerup',()=>{if(!movingRow)return;movingRow.classList.remove('is-dragging');movingRow=null;names()});body.querySelectorAll('.column-row').forEach(prepare);document.getElementById('add-column').onclick=()=>{let row=document.getElementById('column-template').content.firstElementChild.cloneNode(true);prepare(row);body.append(row);names()};editor.addEventListener('click',event=>{let button=event.target.closest('.delete-column');if(button){button.closest('.column-row').remove();names()}});editor.querySelector('[name="row_count"]').oninput=syncValueRows;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==button.dataset.tab);if(button.dataset.tab==='values')syncValueRows()});document.getElementById('delete-toggle')?.addEventListener('click',()=>document.getElementById('delete-modal').hidden=false);document.querySelectorAll('#delete-cancel, #delete-cancel-footer').forEach(button=>button.addEventListener('click',()=>document.getElementById('delete-modal').hidden=true));names();
</script>
<script>
document.querySelector('[data-tab="script"]')?.addEventListener('click', () => formulaEditor?.refresh());
const initialEditorTab = @json($activeTab);
if (initialEditorTab !== 'structure') document.querySelector(`[data-tab="${initialEditorTab}"]`)?.click();
</script>
@endsection
